version: "3"
services:
  eureka:
    image: registry.cn-hangzhou.aliyuncs.com/weilus923/eureka:1.0
    container_name: eureka
    ports:
      - 8761:8761
    environment:
      - EUREKA_INSTANCE_IP-ADDRESS=192.168.198.128
      - EUREKA_IP=192.168.198.3
    volumes:
      - /data/logs:/data/logs

#  gateway:
#    image: registry.cn-hangzhou.aliyuncs.com/weilus923/gateway:1.0
#    container_name: gateway
#    ports:
#      - 8088:8088
#    environment:
#      - EUREKA_INSTANCE_IP-ADDRESS=192.168.198.128
#    volumes:
#      - /data/logs:/data/logs
#    depends_on:
#      - eureka

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - /data/mysql/mysql-cnf:/etc/mysql/conf.d
      - /data/mysql/mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=weilus
    privileged: true


  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass '123456'
    ports:
      - 6379:6379
    environment:
      - /data/redis/redis-data:/data


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

