version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - /data/mysql/mysql-cnf:/etc/mysql/conf.d
      - /data/mysql/mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=weilus
    privileged: true

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass '123456'
    ports:
      - 6379:6379
    environment:
      - /data/redis/redis-data:/data


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

