apiVersion: v1
kind: Service
metadata:
  name: eureka-server1
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
    nodePort: 30001
  type: NodePort
  selector:
    app: weilus.cloud-eureka1
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server2
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  type: NodePort
  selector:
    app: weilus.cloud-eureka2