apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-eureka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-eureka1
  template:
    metadata:
      labels:
        app: weilus.cloud-eureka1
    spec:
      containers:
      - name: eureka
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/eureka:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.96.192.151:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-eureka2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-eureka2
  template:
    metadata:
      labels:
        app: weilus.cloud-eureka2
    spec:
      containers:
      - name: eureka
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/eureka:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.103.239.44:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
