apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-config
  template:
    metadata:
      labels:
        app: weilus.cloud-config
    spec:
      containers:
      - name: config
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/config:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.103.16.92:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-gateway
  template:
    metadata:
      labels:
        app: weilus.cloud-gateway
    spec:
      containers:
      - name: gateway
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/gateway:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.103.16.92:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-auth
  template:
    metadata:
      labels:
        app: weilus.cloud-auth
    spec:
      containers:
      - name: auth
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/auth:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.103.16.92:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key