apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
  namespace: netflix-cloud
spec:
  ports:
  - port: 8761
    targetPort: 8761
  clusterIP: None
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: netflix-cloud
spec:
  serviceName: eureka-svc
  replicas: 3
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
      containers:
      - name: k8seureka
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/eureka:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.96.200.202:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: netflix-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
      containers:
      - name: config
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/config:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@eureka-0.eureka-svc.netflix-cloud.svc.cluster.local:8761/eureka/,http://eureka:123456@eureka-1.eureka-svc.netflix-cloud.svc.cluster.local:8761/eureka/,http://eureka:123456@eureka-2.eureka-svc.netflix-cloud.svc.cluster.local:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: netflix-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
      containers:
      - name: gateway
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/gateway:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@eureka-0.eureka-svc.netflix-cloud.svc.cluster.local:8761/eureka/,http://eureka:123456@eureka-1.eureka-svc.netflix-cloud.svc.cluster.local:8761/eureka/,http://eureka:123456@eureka-2.eureka-svc.netflix-cloud.svc.cluster.local:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: netflix-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
      containers:
      - name: oauth
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/auth:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@eureka-0.eureka-svc.netflix-cloud.svc.cluster.local:8761/eureka/,http://eureka:123456@eureka-1.eureka-svc.netflix-cloud.svc.cluster.local:8761/eureka/,http://eureka:123456@eureka-2.eureka-svc.netflix-cloud.svc.cluster.local:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
