apiVersion: v1
kind: Service
metadata:
  name: eureka-server1
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
    nodePort: 38761
  type: NodePort
  clusterIP: 10.96.200.201
  selector:
    app: weilus.cloud-eureka1
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server2
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  type: ClusterIP
  clusterIP: 10.96.200.202
  selector:
    app: weilus.cloud-eureka2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-eureka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-eureka1
  template:
    metadata:
      labels:
        app: weilus.cloud-eureka1
    spec:
      containers:
      - name: eureka
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/eureka:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.96.200.202:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-eureka2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-eureka2
  template:
    metadata:
      labels:
        app: weilus.cloud-eureka2
    spec:
      containers:
      - name: eureka
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/eureka:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.96.200.201:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-config
  template:
    metadata:
      labels:
        app: weilus.cloud-config
    spec:
      containers:
      - name: config
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/config:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.96.200.201:8761/eureka/,http://eureka:123456@10.96.200.202:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-gateway
  template:
    metadata:
      labels:
        app: weilus.cloud-gateway
    spec:
      containers:
      - name: gateway
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/gateway:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.96.200.201:8761/eureka/,http://eureka:123456@10.96.200.202:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilus.cloud-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-auth
  template:
    metadata:
      labels:
        app: weilus.cloud-auth
    spec:
      containers:
      - name: auth
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/auth:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:123456@10.96.200.201:8761/eureka/,http://eureka:123456@10.96.200.202:8761/eureka/
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key