server:
  port: 8761

info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: eureka

eureka:
  server:
    enable-self-preservation: false #关闭eureka的自我保护 踢出已关闭的节点
    eviction-interval-timer-in-ms: 10000 #清理间隔时间，单位为毫秒
  instance:
    lease-renewal-interval-in-seconds: 10 #租赁更新时间间隔，默认30，即10秒发送一次心跳
    lease-expiration-duration-in-seconds: 60  #租期到期时间，默认90秒
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

endpoints:
  restart:
    enabled: false

logging:
  file: ${log.dir:/data/logs}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    com.netflix.eureka: ERROR
    org.springframework: INFO